name: "Build Test"

on: workflow_dispatch

jobs:
  build-test:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-24.04" # Build AppImage and RPM on 24.04
            args: "--bundles appimage,rpm"
            target: "x86_64-unknown-linux-gnu"

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      sign-binaries: true
      asset-prefix: "handy-test"
      upload-artifacts: true
      is-debug-build: ${{ contains(matrix.args, '--debug') }}
    secrets: inherit
